# Generated by Django 3.1.7 on 2021-04-19 00:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_auto_20210405_0146'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, unique=True, verbose_name='Haber Başlığı ')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='uzantı')),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Öne çıkarma')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('backimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='ana resim "1920-1100"')),
                ('intro', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik')),
                ('summary', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Haber Sahibi')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Haber yazısı',
                'verbose_name_plural': 'Haber Yazıları',
                'ordering': ['title'],
            },
        ),
    ]
