# Generated by Django 3.1.7 on 2021-04-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0003_auto_20210419_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='backimage',
            field=models.ImageField(null=True, upload_to='', verbose_name='ana resim "1920-1100"'),
        ),
    ]
