# Generated by Django 3.1.7 on 2021-04-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0005_auto_20210430_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='sliderimage',
            field=models.ImageField(null=True, upload_to='', verbose_name='slider resmi "800-1100"'),
        ),
    ]
