# Generated by Django 3.1.7 on 2021-04-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0006_newsmodel_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='sliderimage',
        ),
    ]
