# Generated by Django 3.1.7 on 2021-05-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0007_remove_newsmodel_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='sliderhaber',
        ),
    ]
