# Generated by Django 3.1.7 on 2021-03-28 14:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('profiles', '0003_auto_20210319_0348'),
        ('bilgi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='informationTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='İnformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, unique=True, verbose_name='Ana Başlık ')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='uzantı')),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Öne çıkarma')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Başlık Sahibi')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Bilgi yazısı',
                'verbose_name_plural': 'Bilgi Yazıları',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
