# Generated by Django 3.1.7 on 2021-03-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgi', '0002_auto_20210328_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationtextmodel',
            name='dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informationtext', to='bilgi.i̇nformationmodel'),
        ),
    ]
