# Generated by Django 3.1.7 on 2021-03-31 10:33

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgi', '0003_informationtextmodel_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationtextmodel',
            name='backimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='informationtextmodel',
            name='imagatext',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='informationtextmodel',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='informationtextmodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, unique=True, verbose_name='Ana Başlık '),
        ),
        migrations.AlterField(
            model_name='informationtextmodel',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
