# Generated by Django 3.1.7 on 2021-03-31 10:46

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgi', '0004_auto_20210331_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationtextmodel',
            name='imagatext',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informationtextmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='informationtextmodel',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
