# Generated by Django 3.1.7 on 2021-03-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgi', '0005_auto_20210331_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationtextmodel',
            name='title',
        ),
    ]
