# Generated by Django 3.1.7 on 2021-03-31 21:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgi', '0007_auto_20210331_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇nformationmodel',
            name='backimage',
            field=models.ImageField(null=True, upload_to='', verbose_name='ana  resim'),
        ),
        migrations.AddField(
            model_name='i̇nformationmodel',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='içerik'),
        ),
    ]
