# Generated by Django 3.1.7 on 2021-04-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgi', '0010_auto_20210401_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇nformationmodel',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
