# Generated by Django 3.1.7 on 2021-04-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgi', '0011_i̇nformationmodel_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='informationTextModel',
        ),
    ]
