# Generated by Django 3.1.7 on 2021-04-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210404_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='abaout',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Hakkında'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Resmi'),
        ),
    ]
