# Generated by Django 3.1.7 on 2021-03-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20210319_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Ana Başlık ')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Öne Çıkar')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('main_context', models.TextField(blank=True, null=True, verbose_name='Giriş Paragrafı  Ekleyin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Başlık Sahibi')),
            ],
            options={
                'verbose_name': 'Akademi yazısı',
                'verbose_name_plural': 'Akademi yazıları',
                'ordering': ['title'],
            },
        ),
    ]
