# Generated by Django 3.1.7 on 2021-03-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210319_0348'),
        ('dictionary', '0002_auto_20210319_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerinlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Öne çıkarma')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('main_context', models.TextField(blank=True, null=True, verbose_name='Görüşü')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Görüş Sahibi')),
            ],
        ),
    ]
