# Generated by Django 3.1.7 on 2021-03-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_answerinlinemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerinlinemodel',
            options={'ordering': ['created_date'], 'verbose_name': 'Cevap', 'verbose_name_plural': 'Cevaplar'},
        ),
        migrations.AddField(
            model_name='answerinlinemodel',
            name='dictionary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionaryanswers', to='dictionary.dictionarymodel'),
        ),
    ]
