# Generated by Django 3.1.7 on 2021-03-20 11:34

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('dictionary', '0005_auto_20210320_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionarymodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='answerinlinemodel',
            name='main_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
