# Generated by Django 3.1.7 on 2021-03-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20210320_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionarymodel',
            options={'ordering': ['title'], 'verbose_name': 'Sözlük yazısı', 'verbose_name_plural': 'Sözlük Yazıları'},
        ),
    ]
