# Generated by Django 3.1.7 on 2021-04-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_dictionarymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionarymodel',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='dictionarymodel',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='dictionarymodel',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
