# Generated by Django 3.1.7 on 2021-04-06 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210405_0146'),
        ('dictionary', '0011_auto_20210405_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('main_context', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Görüş Sahibi')),
                ('dictionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionaryreported', to='dictionary.dictionarymodel')),
            ],
        ),
    ]
