# Generated by Django 3.1.7 on 2021-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_repormodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repormodel',
            options={'ordering': ['created_date'], 'verbose_name': 'Şikayet', 'verbose_name_plural': 'Şikayetler'},
        ),
        migrations.AddField(
            model_name='repormodel',
            name='olumlu',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='olumsuz bulundu'),
        ),
        migrations.AddField(
            model_name='repormodel',
            name='olumsuz',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Olumlu bulundu'),
        ),
    ]
