# Generated by Django 3.1.7 on 2021-04-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_repormodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repormodel',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('olumlu', 'Olumlu'), ('olumsuz', 'Olumsuz')], default='beklemede', max_length=50, verbose_name='Durum'),
        ),
    ]
